version: '3'

services:
  app:
    build: .
    volumes:
      - ./../:/app
    ports:
      - "9501:9501"
    container_name: test_dbal_swoole_pgsql_driver
  dbhost:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    expose:
      - "5432"
    container_name: test_dbal_swoole_pgsql_driver_db
